package Vistas;

import Controles.AlumnoData;
import Controles.Conexion;
import Controles.CursadaData;
import Controles.MateriaData;
import Modelos.Alumno;
import Modelos.Cursada;
import Modelos.Materia;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

public class VConsultas extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private ArrayList<Cursada> listaCursada;
    private ArrayList<Materia> listaMaterias;
    private ArrayList<Alumno> listaAlumnos;
    private CursadaData cursadaData;
    private MateriaData materiaData;
    private AlumnoData alumnoData;
    private Conexion conexion;
    

    public VConsultas() {
        initComponents();
        try {
        conexion=new Conexion();
        modelo=new DefaultTableModel();
        
        cursadaData=new CursadaData(conexion);
        listaCursada=(ArrayList)cursadaData.obtenerCursadas();
        
        materiaData=new MateriaData(conexion);
        listaMaterias=(ArrayList)materiaData.obtenerMaterias();
        
        alumnoData=new AlumnoData(conexion);
        listaAlumnos=(ArrayList)alumnoData.obtenerAlumnos();
        
        cargarMaterias();
        armaCabeceraTabla();
        cargarDatos();
        } catch (ClassNotFoundException ex) {
            System.out.println("error" + ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbMateria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaAlumMat = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Listado de Alumnos por Materia");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Materia");

        jcbMateria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMateriaActionPerformed(evt);
            }
        });

        jtListaAlumMat.setBackground(new java.awt.Color(153, 204, 255));
        jtListaAlumMat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtListaAlumMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtListaAlumMat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jtListaAlumMat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(64, 64, 64)
                        .addComponent(jcbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMateriaActionPerformed
        cargarDatos();
    }//GEN-LAST:event_jcbMateriaActionPerformed

    public void cargarMaterias(){
        
        for (Materia item:listaMaterias){
            jcbMateria.addItem(item);
        }
    }
    
    public void armaCabeceraTabla(){
    
        ArrayList<Object> columns=new ArrayList<Object>();
        columns.add("IdAlumno");
        columns.add("Apellido");
        columns.add("Nombre");
        columns.add("Nota");
        
        for(Object it:columns){
        
            modelo.addColumn(it);
        }
        
        jtListaAlumMat.setModel(modelo);
    }
    
    public void borrarFilasTabla(){
    
        int a=modelo.getRowCount()-1;
        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
            
        }
    }
    
    public void cargarDatos(){
    
        borrarFilasTabla();
        
        Materia mat=(Materia)jcbMateria.getSelectedItem();
        
        for (Cursada m:listaCursada) {
            
            if (m.getMateria().getIdMateria()==mat.getIdMateria()) {                
                modelo.addRow(new Object[]{m.getAlumno().getIdAlumno(),m.getAlumno().getApellido(),m.getAlumno().getNombre(),m.getNota()});
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Materia> jcbMateria;
    private javax.swing.JTable jtListaAlumMat;
    // End of variables declaration//GEN-END:variables
}
