/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controles.Conexion;
import Controles.CursadaData;
import Controles.MateriaData;
import Modelos.Alumno;
import Modelos.Cursada;
import Modelos.Materia;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo_000
 */
public class VConsultas extends javax.swing.JInternalFrame {
   private DefaultTableModel modelo;
    /**
     * Creates new form VConsultas
     */
    public VConsultas() {
        initComponents();
        Conexion c = new Conexion();
        MateriaData mData = new MateriaData(c);
        
        this.cargarMaterias();
        modelo = new DefaultTableModel();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbMateria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaAlumMat = new javax.swing.JTable();
        jbVer = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Listado de Alumnos por Materia");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Materia");

        jcbMateria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtListaAlumMat.setBackground(new java.awt.Color(153, 204, 255));
        jtListaAlumMat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtListaAlumMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtListaAlumMat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jtListaAlumMat);

        jbVer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbVer.setText("Ver");
        jbVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(jcbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jbVer))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbVer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerActionPerformed
        // TODO add your handling code here:
        borrarFilasT();
        cargarTabla();
    }//GEN-LAST:event_jbVerActionPerformed
  private void armarCabecera(){
        ArrayList<Object>columnas = new ArrayList<>();
        columnas.add("ID");
        columnas.add("Nombre");
        columnas.add("Nota");
        for(Object titulo: columnas){
            modelo.addColumn(titulo);
        }
        jtListaAlumMat.setModel(modelo);
    }
    public void cargarMaterias(){
          Conexion c = new Conexion();
          MateriaData mData = new MateriaData(c);
          ArrayList<Materia>lista = (ArrayList)mData.obtenerMaterias();
          for(Materia mat: lista){
              jcbMateria.addItem(mat);
          }
      }
    public void borrarFilasT(){
    int fila = modelo.getRowCount()-1;
    for(int i=fila; i>=0; i--){
       modelo.removeRow(i);
    }
}
private void cargarTabla(){
    Conexion c = new Conexion();
    CursadaData cd = new CursadaData(c);
    Materia m = (Materia)jcbMateria.getSelectedItem();
    int id = m.getIdMateria();
    ArrayList<Cursada>listCurs = cd.obtenerCursadasxMateria(id);
    for(Cursada curs: listCurs){
        modelo.addRow(new Object[]{(curs.getAlumno()).getIdAlumno(), (curs.getAlumno()).getNombre(), curs.getNota()});
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbVer;
    private javax.swing.JComboBox<Materia> jcbMateria;
    private javax.swing.JTable jtListaAlumMat;
    // End of variables declaration//GEN-END:variables
}
